// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAMN_L-_RY5EXhZ2xq_vB3M3m7ECGti84',
    appId: '1:1068665441363:web:62c0f5929b38bc73744aa6',
    messagingSenderId: '1068665441363',
    projectId: 'fitness-pulse-2765d',
    authDomain: 'fitness-pulse-2765d.firebaseapp.com',
    storageBucket: 'fitness-pulse-2765d.firebasestorage.app',
    measurementId: 'G-S4XM9S3PZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKOHjhtL5pB9jX_h-amFYhz3LqX4PMtII',
    appId: '1:1068665441363:android:ea09b825a38c050a744aa6',
    messagingSenderId: '1068665441363',
    projectId: 'fitness-pulse-2765d',
    storageBucket: 'fitness-pulse-2765d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3F4PORQ7Cv7GtS5sk5XM4XWa9A5pmc9I',
    appId: '1:1068665441363:ios:50f5dfbe4cd618be744aa6',
    messagingSenderId: '1068665441363',
    projectId: 'fitness-pulse-2765d',
    storageBucket: 'fitness-pulse-2765d.firebasestorage.app',
    iosBundleId: 'com.example.fitnessPulse',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3F4PORQ7Cv7GtS5sk5XM4XWa9A5pmc9I',
    appId: '1:1068665441363:ios:50f5dfbe4cd618be744aa6',
    messagingSenderId: '1068665441363',
    projectId: 'fitness-pulse-2765d',
    storageBucket: 'fitness-pulse-2765d.firebasestorage.app',
    iosBundleId: 'com.example.fitnessPulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAMN_L-_RY5EXhZ2xq_vB3M3m7ECGti84',
    appId: '1:1068665441363:web:fa23a2387cb3da02744aa6',
    messagingSenderId: '1068665441363',
    projectId: 'fitness-pulse-2765d',
    authDomain: 'fitness-pulse-2765d.firebaseapp.com',
    storageBucket: 'fitness-pulse-2765d.firebasestorage.app',
    measurementId: 'G-QDVVH6RHQC',
  );
}
